# Generated by Django 4.0.5 on 2022-08-11 02:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='users_watchlist',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='/images/default/image.png', upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
